name: Docker Image Publish

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t meesregistry.azurecr.io/final:${{ github.sha }} src/data-tool/
      
    - uses: azure/docker-login@v2
      with:
        login-server: meesregistry.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: docker push meesregistry.azurecr.io/final:${{ github.sha }}
    
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'mees-web'
        publish-profile: ${{ secrets.PUBLISH_PROFILE }}
        images: 'meesregistry.azurecr.io/final:${{ github.sha }}'
